--- 
jobs: 
  build: 
    docker: 
      - 
        image: "circleci/openjdk:8-jdk-browsers"
      - 
        image: circleci/mysql:8.0.4
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_ROOT_PASSWORD:  ''
          MYSQL_DATABASE: crud_rest_helloworld
          MYSQL_USER: root
          MYSQL_PASSWORD: ''
    steps: 
      - checkout
      - setup_remote_docker
      - run: 
          name: Wait for Database Connection
          # preinstalled in circleci/* docker image
          command: dockerize -wait tcp://localhost:3306 -timeout 1m
      - run: 
          name: Install MySQL CLI; Import dummy data; run an example query
          command: |
            sudo apt-get install default-mysql-client
            mysql -h 127.0.0.1 -u root -p   crud_rest_helloworld < sql-data/crud_rest_helloworld.sql
            mysql -h 127.0.0.1 -u root -p   --execute="SELECT * FROM crud_rest_helloworld.test"
      - 
        restore_cache: 
          key: "spring-rest-crud-helloworld-{{ checksum \"pom.xml\" }}"
      - 
        run: "mvn dependency:go-offline"
      - 
        save_cache: 
          key: "spring-rest-crud-helloworld-{{ checksum \"pom.xml\" }}"
          paths: 
            - ~/.m2
      - 
        run: 
          command: "if mvn -q -Dexec.executable=\"echo\" -Dexec.args='${project.version}' --non-recursive exec:exec | grep -q \"SNAPSHOT\"; then mvn versions:set -DremoveSnapshot; fi;\n\
              echo $(mvn -q -Dexec.executable=\"echo\" -Dexec.args='${project.version}' --non-recursive exec:exec)-$(echo $CIRCLE_SHA1 | cut -c -7)-$CIRCLE_BUILD_NUM > tempvers.txt\n\
              mvn versions:set -DnewVersion=$(cat tempvers.txt) \n"
          name: "remove snapshot version"
      - 
        run: "mvn package"
      - 
        run: 
          command: |
              cp target/*.jar docker/apps/
              docker login -u $DOCKER_REPO_USERNAME -p $DOCKER_REPO_PASSWORD
              docker build --no-cache -t mrpyaesone25/spring-rest-crud-helloworld:$(cat tempvers.txt) docker
              docker push mrpyaesone25/spring-rest-crud-helloworld:$(cat tempvers.txt)
          name: "Build application Docker image"
    working_directory: ~/spring-rest-crud-helloworld
version: 2